# Generated by Django 5.1.4 on 2025-01-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessgroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
